# -*- coding: utf-8 -*-
"""Prob_and_rand_var.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o3W1sOUqNYrSH0h2cRncWpqW-B2AVjrN
"""


import numpy as np
values = [-1,1]# these are the discrete values of the random variable
probabilities = [0.5,0.5]# these are the probabilities corresponding to the values
sim_result=0
iterations=100000
theo_result=40
for z in range(0,iterations):
   a=np.random.choice(values, 4, p=probabilities)# a is the array containing the required 4 random variables
   b=(sum(a))**4
   sim_result+=b
sim_result/=iterations
print(sim_result,":",theo_result)
